@startuml
'https://plantuml.com/deployment-diagram

database "Jore 4 Database\n(postgres/gis)" as db #business {
    rectangle "Hasura schema" as hasuraschema #lightgray
    rectangle "Backend schema" as backendschema #lightgray
}

database "Jore 3 Database\n(mssql)" as legacydb #business {
    rectangle "Jore 3 schema" as legacyschema #lightgray
}

node "Hasura" as hasura

frame "Frontend\n(React)" as frontend

component "Backend\n(java)" as backend

cloud "HSL-ID" as hslid

cloud "Tile server\n(OSM)" as tile

note right of backend : Not necessarily\na single process

frontend --(0-- hasura : GraphQL

frontend --(0-- tile : HTTP:image/png

hasura <--(0-- backendschema : read-only

hasura <--(0-- hasuraschema : read+write

backend <--(0--> backendschema : read+write

backend <--(0-- legacyschema : read-only

hasura --(0--> backend : HTTP

hslid ... backend : authorizes
hslid ... hasura : authorizes

@enduml
