name: Check renovatebot config

on:
  pull_request:

jobs:
  validate:
    name: Validate renovatebot config
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.3
        with:
          config_file_path: .github/renovate.json5
