name: Check renovatebot config

on:
  pull_request:

jobs:
  validate:
    name: Validate renovatebot config
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Validate
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v2.1.0
        with:
          config_file_path: .github/renovate.json5
