name: Check renovatebot config

on:
  pull_request:

jobs:
  validate:
    name: Validate renovatebot config
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
        with:
          config_file_path: .github/renovate.json5
